name: Sifu
favicon: null
layout_spectrum: 0.10117983887903392
typography_spectrum: 0.629085143096745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.09917882597073913
  lightness: 0.2516182700637728
  saturation: 0.8329891040921211
  rhythmicContrast: 0.06425923458300531
purpose: []
